# Generated by Django 4.2.7 on 2024-05-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpost',
            name='picture',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
